/**
 * Original prompts written for this project — not transcribed from any
 * existing game. The "most likely to..." / superlative prompt structure is
 * a generic, functional format (a fact pattern, not expressive content),
 * so this list sidesteps IP concerns with games that use similar formats.
 */
export const QUESTION_BANK: { text: string; tags: string[] }[] = [
  { text: "Most likely to become a millionaire", tags: ["ambition"] },
  { text: "Most likely to be famous one day", tags: ["ambition"] },
  { text: "Most likely to accidentally start a business empire", tags: ["ambition", "silly"] },
  { text: "Most likely to retire before 40", tags: ["ambition"] },
  { text: "Most likely to still be working at 80 because they love it", tags: ["ambition"] },
  { text: "Most likely to win an award for something completely unexpected", tags: ["ambition", "silly"] },
  { text: "Most likely to run for public office", tags: ["ambition"] },
  { text: "Most likely to write a bestselling novel", tags: ["ambition", "creative"] },
  { text: "Most likely to be the CEO of a company they haven't founded yet", tags: ["ambition"] },
  { text: "Most likely to have a statue built in their honor", tags: ["ambition", "silly"] },

  { text: "Most likely to survive a zombie apocalypse", tags: ["silly", "hypothetical"] },
  { text: "Most likely to accidentally join a cult", tags: ["silly", "hypothetical"] },
  { text: "Most likely to get lost in their own neighborhood", tags: ["silly"] },
  { text: "Most likely to fight a goose and lose", tags: ["silly"] },
  { text: "Most likely to become a supervillain instead of a superhero", tags: ["silly", "hypothetical"] },
  { text: "Most likely to survive being stranded on a desert island", tags: ["silly", "hypothetical"] },
  { text: "Most likely to win a staring contest with a cat", tags: ["silly"] },
  { text: "Most likely to be the last one standing in a game of hide and seek", tags: ["silly"] },
  { text: "Most likely to get kicked out of a museum", tags: ["silly"] },
  { text: "Most likely to talk their way out of a speeding ticket", tags: ["silly"] },
  { text: "Most likely to accidentally set off a fire alarm", tags: ["silly"] },
  { text: "Most likely to win a hot dog eating contest", tags: ["silly"] },
  { text: "Most likely to be recognized by a barista without ordering", tags: ["silly"] },
  { text: "Most likely to befriend a raccoon", tags: ["silly"] },
  { text: "Most likely to end up on a reality TV show", tags: ["silly"] },
  { text: "Most likely to win the lottery and lose the ticket", tags: ["silly"] },
  { text: "Most likely to talk their way out of any situation", tags: ["silly", "hypothetical"] },
  { text: "Most likely to be arrested for something ridiculous", tags: ["silly"] },
  { text: "Most likely to trip in front of their crush", tags: ["silly"] },
  { text: "Most likely to fall asleep at a party", tags: ["silly"] },

  { text: "Most likely to become a world-famous chef", tags: ["talent"] },
  { text: "Most likely to win a talent show", tags: ["talent"] },
  { text: "Most likely to be a great stand-up comedian", tags: ["talent"] },
  { text: "Most likely to master a musical instrument overnight", tags: ["talent"] },
  { text: "Most likely to be an Olympic athlete", tags: ["talent"] },
  { text: "Most likely to win a dance competition", tags: ["talent"] },
  { text: "Most likely to paint a masterpiece", tags: ["talent", "creative"] },
  { text: "Most likely to be a professional gamer", tags: ["talent"] },
  { text: "Most likely to have the best karaoke voice at the party", tags: ["talent"] },
  { text: "Most likely to be a natural at any sport they try", tags: ["talent"] },
  { text: "Most likely to fix anything with duct tape", tags: ["talent", "silly"] },
  { text: "Most likely to give the best advice", tags: ["talent", "kindness"] },
  { text: "Most likely to be a walking encyclopedia", tags: ["talent"] },
  { text: "Most likely to solve a Rubik's cube in under a minute", tags: ["talent"] },
  { text: "Most likely to be great at improv", tags: ["talent"] },

  { text: "Most likely to cry at a movie and deny it", tags: ["personality"] },
  { text: "Most likely to remember everyone's birthday", tags: ["personality", "kindness"] },
  { text: "Most likely to give the best hugs", tags: ["personality", "kindness"] },
  { text: "Most likely to be the mom or dad friend of the group", tags: ["personality"] },
  { text: "Most likely to plan the perfect surprise party", tags: ["personality", "kindness"] },
  { text: "Most likely to talk to strangers and make a new best friend", tags: ["personality"] },
  { text: "Most likely to never stop smiling", tags: ["personality"] },
  { text: "Most likely to have the most contagious laugh", tags: ["personality"] },
  { text: "Most likely to give up their seat for someone else", tags: ["personality", "kindness"] },
  { text: "Most likely to organize a group trip and actually pull it off", tags: ["personality"] },
  { text: "Most likely to be the peacemaker in an argument", tags: ["personality", "kindness"] },
  { text: "Most likely to tell the same story twice without realizing", tags: ["personality", "silly"] },
  { text: "Most likely to be brutally honest when you ask for their opinion", tags: ["personality"] },
  { text: "Most likely to overthink a simple decision", tags: ["personality"] },
  { text: "Most likely to be the first one on the dance floor", tags: ["personality"] },
  { text: "Most likely to be the last one to leave a party", tags: ["personality"] },
  { text: "Most likely to fall in love at first sight", tags: ["personality", "dating"] },
  { text: "Most likely to text back three days later", tags: ["personality", "silly"] },
  { text: "Most likely to have a secret talent nobody knows about", tags: ["personality"] },
  { text: "Most likely to become best friends with a total stranger on a plane", tags: ["personality"] },

  { text: "Most likely to become an astronaut", tags: ["hypothetical"] },
  { text: "Most likely to live off the grid", tags: ["hypothetical"] },
  { text: "Most likely to move to a different country on a whim", tags: ["hypothetical"] },
  { text: "Most likely to start their own reality show", tags: ["hypothetical"] },
  { text: "Most likely to invent something that changes the world", tags: ["hypothetical", "ambition"] },
  { text: "Most likely to be a spy", tags: ["hypothetical"] },
  { text: "Most likely to survive a week with no phone", tags: ["hypothetical"] },
  { text: "Most likely to win an argument with a vending machine", tags: ["hypothetical", "silly"] },
  { text: "Most likely to convince everyone the moon landing was fake, as a joke", tags: ["hypothetical", "silly"] },
  { text: "Most likely to become a professional treasure hunter", tags: ["hypothetical"] },
  { text: "Most likely to open a food truck", tags: ["hypothetical"] },
  { text: "Most likely to become fluent in a language just from watching TV", tags: ["hypothetical"] },
  { text: "Most likely to time travel and mess something up", tags: ["hypothetical", "silly"] },
  { text: "Most likely to win a debate against a lawyer", tags: ["hypothetical"] },
  { text: "Most likely to build a treehouse and actually live in it", tags: ["hypothetical", "silly"] },

  { text: "Most likely to be late to their own wedding", tags: ["silly"] },
  { text: "Most likely to forget their own phone number", tags: ["silly"] },
  { text: "Most likely to show up in pajamas by accident", tags: ["silly"] },
  { text: "Most likely to bring the wrong item to a potluck", tags: ["silly"] },
  { text: "Most likely to laugh at the wrong moment", tags: ["silly"] },
  { text: "Most likely to have the messiest car", tags: ["silly"] },
  { text: "Most likely to have the cleanest room", tags: ["silly"] },
  { text: "Most likely to binge an entire show in one night", tags: ["silly"] },
  { text: "Most likely to fall for an obvious prank", tags: ["silly"] },
  { text: "Most likely to pull off the perfect prank", tags: ["silly"] },
  { text: "Most likely to be the reason the group chat is chaotic", tags: ["silly"] },
  { text: "Most likely to send a text to the wrong person", tags: ["silly"] },
  { text: "Most likely to have 100 unread emails", tags: ["silly"] },
  { text: "Most likely to know a surprising amount about a niche topic", tags: ["silly"] },
  { text: "Most likely to win any game night, no matter the game", tags: ["silly", "talent"] },
  { text: "Most likely to flip a table over losing a board game", tags: ["silly"] },
  { text: "Most likely to fall asleep during a movie every single time", tags: ["silly"] },
  { text: "Most likely to eat dessert first", tags: ["silly"] },
  { text: "Most likely to have the best hidden dance moves", tags: ["silly", "talent"] },
  { text: "Most likely to become a meme", tags: ["silly"] },

  { text: "Most likely to be everyone's emergency contact", tags: ["kindness"] },
  { text: "Most likely to notice when someone's having a bad day", tags: ["kindness"] },
  { text: "Most likely to drop everything to help a friend", tags: ["kindness"] },
  { text: "Most likely to volunteer for something without being asked", tags: ["kindness"] },
  { text: "Most likely to adopt every stray animal they meet", tags: ["kindness"] },
  { text: "Most likely to give their last dollar to someone in need", tags: ["kindness"] },
  { text: "Most likely to write a heartfelt card instead of buying a gift", tags: ["kindness", "creative"] },
  { text: "Most likely to check in on you a week after something bad happened", tags: ["kindness"] },
  { text: "Most likely to be a great mentor", tags: ["kindness", "talent"] },
  { text: "Most likely to make a new person feel instantly welcome", tags: ["kindness"] },

  { text: "Most likely to be the reason a trip gets memorable (in a good way)", tags: ["personality"] },
  { text: "Most likely to plan every detail of a trip in advance", tags: ["personality"] },
  { text: "Most likely to show up with zero plan and wing it", tags: ["personality"] },
  { text: "Most likely to be awake at 3am for no reason", tags: ["silly"] },
  { text: "Most likely to have a hidden stash of snacks", tags: ["silly"] },
  { text: "Most likely to know the lyrics to every song on the radio", tags: ["talent"] },
  { text: "Most likely to start a band, even without knowing an instrument", tags: ["silly", "talent"] },
  { text: "Most likely to have the best comeback in an argument", tags: ["talent"] },
  { text: "Most likely to be recruited by a cult for their charisma", tags: ["silly"] },
  { text: "Most likely to convince a group to do something questionable", tags: ["silly"] },
  { text: "Most likely to be the voice of reason in a bad idea", tags: ["personality"] },
  { text: "Most likely to have the bad idea in the first place", tags: ["silly"] },
  { text: "Most likely to become an influencer overnight", tags: ["ambition", "silly"] },
  { text: "Most likely to quit social media and never look back", tags: ["personality"] },
  { text: "Most likely to be featured on the news for something heroic", tags: ["kindness"] },
  { text: "Most likely to be featured on the news for something ridiculous", tags: ["silly"] },
  { text: "Most likely to win a pie eating contest", tags: ["silly"] },
  { text: "Most likely to become a professional couch potato", tags: ["silly"] },
  { text: "Most likely to run a marathon on a dare", tags: ["silly", "ambition"] },
  { text: "Most likely to open a bakery someday", tags: ["ambition"] },

  { text: "Most likely to be the group's designated photographer", tags: ["personality"] },
  { text: "Most likely to have the best photo memory", tags: ["talent"] },
  { text: "Most likely to be unbothered in any crisis", tags: ["personality"] },
  { text: "Most likely to panic first in any crisis", tags: ["personality", "silly"] },
  { text: "Most likely to give a TED talk", tags: ["ambition", "talent"] },
  { text: "Most likely to become a professor", tags: ["ambition"] },
  { text: "Most likely to homeschool their future kids", tags: ["ambition"] },
  { text: "Most likely to raise the most well-behaved pet", tags: ["personality"] },
  { text: "Most likely to have a pet that runs the household", tags: ["silly"] },
  { text: "Most likely to become a plant parent with 50 plants", tags: ["silly"] },
  { text: "Most likely to kill every plant they own", tags: ["silly"] },
  { text: "Most likely to win an eating challenge on TV", tags: ["silly"] },
  { text: "Most likely to be recognized in public for something they did years ago", tags: ["silly"] },
  { text: "Most likely to still be in touch with everyone here in 20 years", tags: ["kindness"] },
  { text: "Most likely to throw the best party", tags: ["personality"] },

  // "nsfw" is reserved for genuinely explicit/adult content — sexual
  // history, nudity, that kind of thing. Dating/romance content that isn't
  // actually adult in nature lives under "dating" instead, so a group with
  // no relevant dating life (age, whatever the reason) can exclude it
  // without also losing the family-friendly bulk of the bank.
  { text: "Most likely to have the most interesting bedroom stories", tags: ["nsfw"] },
  { text: "Most likely to have a wild story from a one-night stand", tags: ["nsfw"] },
  { text: "Most likely to get naked at a party on a dare", tags: ["nsfw", "silly"] },
  { text: "Most likely to have a walk of shame story", tags: ["nsfw"] },
  { text: "Most likely to have snuck someone out through a window", tags: ["nsfw", "silly"] },
  { text: "Most likely to have been caught making out somewhere they shouldn't have", tags: ["nsfw"] },
  { text: "Most likely to have a friends-with-benefits story", tags: ["nsfw"] },
  { text: "Most likely to have had a wardrobe malfunction at the worst possible time", tags: ["nsfw", "silly"] },
  { text: "Most likely to have a \"we shouldn't have, but we did\" story", tags: ["nsfw"] },
  { text: "Most likely to have hooked up with someone they met that same night", tags: ["nsfw"] },
  { text: "Most likely to have had a summer fling that got way more intense than expected", tags: ["nsfw", "dating"] },
  { text: "Most likely to have a spicy text thread they'd never show their parents", tags: ["nsfw"] },
  { text: "Most likely to have snuck out for a late-night rendezvous", tags: ["nsfw"] },
  { text: "Most likely to have a hookup story involving a costume party", tags: ["nsfw", "silly"] },
  { text: "Most likely to have a secret hookup they never told anyone about", tags: ["nsfw"] },

  { text: "Most likely to be the last one standing after a night out", tags: ["alcohol"] },
  { text: "Most likely to have the craziest drunk story", tags: ["alcohol"] },
  { text: "Most likely to become everyone's best friend after two drinks", tags: ["alcohol"] },
  { text: "Most likely to black out and not remember the night", tags: ["alcohol"] },
  { text: "Most likely to be the designated driver every single time", tags: ["alcohol", "kindness"] },
  { text: "Most likely to start a conga line at a bar", tags: ["alcohol", "silly"] },
  { text: "Most likely to order the same drink every single time", tags: ["alcohol"] },
  { text: "Most likely to cry after one too many drinks", tags: ["alcohol"] },
  { text: "Most likely to wake up with a mystery bruise after a night out", tags: ["alcohol", "silly"] },
  { text: "Most likely to become a bartender's favorite regular", tags: ["alcohol"] },
  { text: "Most likely to mix drinks that should never be mixed", tags: ["alcohol", "silly"] },
  { text: "Most likely to organize the group's next bar crawl", tags: ["alcohol"] },

  { text: "Most likely to get away with a crime", tags: ["criminal"] },
  { text: "Most likely to be the mastermind of a heist", tags: ["criminal"] },
  { text: "Most likely to end up on a most-wanted list for something ridiculous", tags: ["criminal", "silly"] },
  { text: "Most likely to talk their way out of an arrest", tags: ["criminal"] },
  { text: "Most likely to accidentally commit a felony", tags: ["criminal", "silly"] },
  { text: "Most likely to be the getaway driver", tags: ["criminal"] },
  { text: "Most likely to snitch under pressure", tags: ["criminal"] },
  { text: "Most likely to start an underground black-market business", tags: ["criminal"] },
  { text: "Most likely to have a fake ID story", tags: ["criminal", "silly"] },
  { text: "Most likely to be the prime suspect in a mystery", tags: ["criminal"] },
  { text: "Most likely to break someone out of jail", tags: ["criminal"] },
  { text: "Most likely to run a scheme that somehow works", tags: ["criminal"] },

  { text: "Most likely to be a surprisingly good kisser", tags: ["dating"] },
  { text: "Most likely to have the most followers on a dating app", tags: ["dating"] },
  { text: "Most likely to send a risky text at 2am", tags: ["dating"] },
  { text: "Most likely to have used a cheesy pickup line and had it work", tags: ["dating"] },
  { text: "Most likely to have a secret admirer they don't know about", tags: ["dating"] },
  { text: "Most likely to be the reason for a scandalous rumor", tags: ["silly"] },
  { text: "Most likely to have a folder of texts they'd never want read aloud", tags: ["silly"] },
  { text: "Most likely to have a much wilder past than they let on", tags: ["personality"] },
  { text: "Most likely to make the first move", tags: ["dating"] },

  { text: "Most likely to fall for someone at this table", tags: ["dating"] },
  { text: "Most likely to text an ex at the worst possible time", tags: ["dating"] },
  { text: "Most likely to have a situationship they can't fully explain", tags: ["dating"] },
  { text: "Most likely to fall in love on a plane", tags: ["dating"] },
  { text: "Most likely to have a whirlwind romance", tags: ["dating"] },
  { text: "Most likely to get married on a whim in Vegas", tags: ["dating"] },
  { text: "Most likely to still have feelings for their first crush", tags: ["dating"] },
  { text: "Most likely to have a dating app horror story", tags: ["dating"] },
  { text: "Most likely to be swept off their feet by a total stranger", tags: ["dating"] },
  { text: "Most likely to break someone's heart without meaning to", tags: ["dating"] },
  { text: "Most likely to have the messiest breakup story", tags: ["dating"] },
  { text: "Most likely to reconnect with an ex years from now", tags: ["dating"] },

  // Expansion batch — same original-content policy as above.
  { text: "Most likely to turn a hobby into a full-blown art form", tags: ["creative", "talent"] },
  { text: "Most likely to redecorate their entire room on a whim", tags: ["creative"] },
  { text: "Most likely to turn a group chat into a comic strip", tags: ["creative", "silly"] },
  { text: "Most likely to design their own tattoo", tags: ["creative"] },
  { text: "Most likely to start a podcast about something oddly specific", tags: ["creative", "silly"] },
  { text: "Most likely to write and perform their own wedding vows", tags: ["creative", "dating"] },
  { text: "Most likely to build something impressive out of household junk", tags: ["creative", "talent"] },
  { text: "Most likely to come up with the best team name every time", tags: ["creative", "silly"] },
  { text: "Most likely to doodle through an entire meeting", tags: ["creative", "silly"] },
  { text: "Most likely to direct their own short film", tags: ["creative", "ambition"] },
  { text: "Most likely to remix a nursery rhyme into a banger", tags: ["creative", "silly"] },
  { text: "Most likely to have the most creative excuse for being late", tags: ["creative", "silly"] },
  { text: "Most likely to turn a bad date into a great story", tags: ["creative", "dating"] },
  { text: "Most likely to have the best Halloween costume every year", tags: ["creative", "talent"] },
  { text: "Most likely to name their future pet something absurdly specific", tags: ["creative", "silly"] },

  { text: "Most likely to have a five-year plan taped to their wall", tags: ["ambition"] },
  { text: "Most likely to negotiate their own salary before their first day", tags: ["ambition"] },
  { text: "Most likely to turn a side hustle into a real company", tags: ["ambition"] },
  { text: "Most likely to read a self-help book cover to cover in one sitting", tags: ["ambition"] },
  { text: "Most likely to wake up at 5am just to get ahead", tags: ["ambition"] },
  { text: "Most likely to have a vision board that actually works", tags: ["ambition"] },
  { text: "Most likely to start three businesses before finishing one", tags: ["ambition", "silly"] },
  { text: "Most likely to out-network everyone in the room", tags: ["ambition", "personality"] },
  { text: "Most likely to ask for a promotion and get it", tags: ["ambition"] },
  { text: "Most likely to turn a rejection into motivation", tags: ["ambition"] },

  { text: "Most likely to survive a week in the wilderness with nothing but a pocketknife", tags: ["hypothetical"] },
  { text: "Most likely to talk their way onto a spaceship", tags: ["hypothetical", "silly"] },
  { text: "Most likely to win a role in a movie by accident", tags: ["hypothetical"] },
  { text: "Most likely to become royalty in another country", tags: ["hypothetical", "silly"] },
  { text: "Most likely to be mistaken for a celebrity", tags: ["hypothetical", "silly"] },
  { text: "Most likely to accidentally end up on the news", tags: ["hypothetical", "silly"] },
  { text: "Most likely to survive a plot twist in a horror movie", tags: ["hypothetical"] },
  { text: "Most likely to be recruited as a secret agent", tags: ["hypothetical"] },
  { text: "Most likely to win a reality competition show", tags: ["hypothetical"] },
  { text: "Most likely to end up the mayor of a small town", tags: ["hypothetical"] },
  { text: "Most likely to become fluent in a made-up language just for fun", tags: ["hypothetical", "silly"] },
  { text: "Most likely to talk their way past a bouncer with no ID", tags: ["hypothetical", "silly"] },

  { text: "Most likely to memorize an entire movie script", tags: ["talent"] },
  { text: "Most likely to win a lip sync battle", tags: ["talent"] },
  { text: "Most likely to juggle literally anything handed to them", tags: ["talent"] },
  { text: "Most likely to be the best at this table at literally any board game", tags: ["talent"] },
  { text: "Most likely to whistle any song on command", tags: ["talent"] },
  { text: "Most likely to do an impression that's scarily accurate", tags: ["talent", "silly"] },
  { text: "Most likely to beatbox better than they let on", tags: ["talent"] },
  { text: "Most likely to nail a cartwheel after a few drinks", tags: ["talent", "silly", "alcohol"] },
  { text: "Most likely to out-cook a professional chef", tags: ["talent"] },
  { text: "Most likely to speak in movie quotes without realizing it", tags: ["talent", "silly"] },

  { text: "Most likely to remember a conversation from years ago word for word", tags: ["personality"] },
  { text: "Most likely to turn any small talk into a deep conversation", tags: ["personality"] },
  { text: "Most likely to have strong opinions about cereal", tags: ["personality", "silly"] },
  { text: "Most likely to apologize to a piece of furniture after bumping into it", tags: ["personality", "silly"] },
  { text: "Most likely to have a signature laugh you'd recognize anywhere", tags: ["personality"] },
  { text: "Most likely to be suspiciously good at reading a room", tags: ["personality"] },
  { text: "Most likely to overpack for a weekend trip", tags: ["personality", "silly"] },
  { text: "Most likely to underpack for a weekend trip", tags: ["personality", "silly"] },
  { text: "Most likely to have a color-coded calendar", tags: ["personality"] },
  { text: "Most likely to lose track of time mid-conversation", tags: ["personality"] },
  { text: "Most likely to give unsolicited but surprisingly accurate advice", tags: ["personality"] },
  { text: "Most likely to text in all lowercase no matter what", tags: ["personality", "silly"] },

  { text: "Most likely to remember how you take your coffee", tags: ["kindness"] },
  { text: "Most likely to save you a seat without being asked", tags: ["kindness"] },
  { text: "Most likely to text \"you good?\" the second something feels off", tags: ["kindness"] },
  { text: "Most likely to give away their umbrella in the rain", tags: ["kindness"] },
  { text: "Most likely to quietly pay for a stranger's coffee", tags: ["kindness"] },
  { text: "Most likely to always have a spare charger for someone else", tags: ["kindness"] },
  { text: "Most likely to talk you out of a bad decision, gently", tags: ["kindness"] },
  { text: "Most likely to show up with soup when you're sick", tags: ["kindness"] },
  { text: "Most likely to remember everyone's food allergies without being told", tags: ["kindness"] },
  { text: "Most likely to be the reason a stray animal has a home now", tags: ["kindness"] },

  { text: "Most likely to narrate their own life like a nature documentary", tags: ["silly"] },
  { text: "Most likely to get into a full argument with an inanimate object", tags: ["silly"] },
  { text: "Most likely to trip over absolutely nothing", tags: ["silly"] },
  { text: "Most likely to have a playlist named something unhinged", tags: ["silly"] },
  { text: "Most likely to lose their phone while holding it", tags: ["silly"] },
  { text: "Most likely to bring snacks to an event and eat them all beforehand", tags: ["silly"] },
  { text: "Most likely to accidentally like a years-old photo while stalking someone's profile", tags: ["silly"] },
  { text: "Most likely to fall for a prank they set up themselves", tags: ["silly"] },
  { text: "Most likely to forget why they walked into a room, every single time", tags: ["silly"] },
  { text: "Most likely to argue passionately about something they Googled five minutes ago", tags: ["silly"] },
  { text: "Most likely to have a wildly specific hill to die on", tags: ["silly", "personality"] },
  { text: "Most likely to own a novelty item they refuse to explain", tags: ["silly"] },

  { text: "Most likely to get a spontaneous tattoo", tags: ["silly"] },
  { text: "Most likely to get a tattoo on their forehead", tags: ["silly"] },
  { text: "Most likely to get a tattoo on their rear", tags: ["silly"] },
  { text: "Most likely to get a tattoo they regret by morning", tags: ["silly", "alcohol"] },
  { text: "Most likely to get matching tattoos with a total stranger", tags: ["silly"] },
  { text: "Most likely to get a tattoo of an ex's name", tags: ["silly", "dating"] },
  { text: "Most likely to have a tattoo with a typo in it", tags: ["silly"] },
  { text: "Most likely to get a tattoo to win a bet", tags: ["silly"] },

  { text: "Most likely to invent a cocktail on the spot", tags: ["alcohol", "creative"] },
  { text: "Most likely to give a heartfelt toast that goes way too long", tags: ["alcohol"] },
  { text: "Most likely to challenge a stranger to a drinking game and win", tags: ["alcohol"] },
  { text: "Most likely to be everyone's ride home, whether they offered or not", tags: ["alcohol", "kindness"] },
  { text: "Most likely to somehow still be dancing at closing time", tags: ["alcohol", "silly"] },
  { text: "Most likely to swear off drinking and be back at it next weekend", tags: ["alcohol", "silly"] },
  { text: "Most likely to bring a flask somewhere it definitely doesn't belong", tags: ["alcohol", "silly"] },
  { text: "Most likely to lose an argument they were clearly winning after one more round", tags: ["alcohol", "silly"] },

  { text: "Most likely to have an alibi ready before anyone asks", tags: ["criminal"] },
  { text: "Most likely to be framed for something they didn't do", tags: ["criminal"] },
  { text: "Most likely to know exactly how to pick a lock", tags: ["criminal", "talent"] },
  { text: "Most likely to run a con without anyone noticing", tags: ["criminal"] },
  { text: "Most likely to be the inside source in a heist movie", tags: ["criminal"] },
  { text: "Most likely to get pulled over and somehow make friends with the cop", tags: ["criminal", "silly"] },
  { text: "Most likely to have a secret double life", tags: ["criminal", "hypothetical"] },
  { text: "Most likely to be the reason the group needs a lawyer on speed dial", tags: ["criminal", "silly"] },

  { text: "Most likely to have a type that never changes", tags: ["dating"] },
  { text: "Most likely to fall for the \"we're just friends\" line", tags: ["dating"] },
  { text: "Most likely to have the most chaotic dating app bio", tags: ["dating", "silly"] },
  { text: "Most likely to get proposed to in an unconventional way", tags: ["dating"] },
  { text: "Most likely to have kissed someone within five minutes of meeting them", tags: ["dating"] },
  { text: "Most likely to leave a party with someone's number", tags: ["dating"] },
  { text: "Most likely to have the most dramatic love story of the group", tags: ["dating"] },
  { text: "Most likely to fall hard and fast, every single time", tags: ["dating"] },

  { text: "Most likely to marry their best friend", tags: ["dating"] },
  { text: "Most likely to still be single by choice and totally fine with it", tags: ["dating"] },
  { text: "Most likely to fall for someone completely wrong for them", tags: ["dating"] },
  { text: "Most likely to know within five minutes if it's not going to work out", tags: ["dating"] },
  { text: "Most likely to write a letter to their future partner", tags: ["dating", "creative"] },
  { text: "Most likely to have a situationship turn into something real", tags: ["dating"] },
  { text: "Most likely to be the one who got away for someone in this room", tags: ["dating"] },
  { text: "Most likely to plan an entire future with someone after one good date", tags: ["dating", "silly"] },
];
